name: auto_size_text
description: Flutter widget that automatically resizes text to fit perfectly within its bounds.
version: 3.1.0
homepage: https://github.com/leisim/auto_size_text

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.6.1

  # Setting to any will let the SDK version define
  # the most compatible version.
  leak_tracker_flutter_testing: ^3.0.9
